# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdoteNaoCompreSITE', '0004_auto_20161014_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DataRegistro', models.DateTimeField(null=True)),
                ('IdCao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.Dog')),
                ('IdInteressado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdProtetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
