# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=20)),
                ('Info', models.CharField(max_length=100)),
                ('Foto', models.FileField(upload_to='Images/%Y/%m/%d')),
                ('Interesse', models.BooleanField(default=False)),
                ('Idade', models.IntegerField(blank=True, null=True)),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=2)),
                ('IdProtetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=30)),
                ('Texto', models.TextField(blank=True)),
                ('DataPublicacao', models.DateTimeField(auto_now=True)),
                ('IdAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
