# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=20)),
                ('Info', models.CharField(max_length=100)),
                ('Foto', models.FileField(upload_to='Images/%Y/%m/%d')),
                ('Interesse', models.BooleanField(default=False)),
                ('Idade', models.IntegerField(blank=True, null=True)),
                ('Peso', models.FloatField(null=True)),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=2)),
                ('DataRegistro', models.DateTimeField(null=True)),
                ('IdProtetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdRaca', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=30)),
                ('Texto', models.TextField(blank=True)),
                ('DataPublicacao', models.DateTimeField(auto_now=True)),
                ('IdAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=100)),
                ('Sigla', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User_extras',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cidade', models.CharField(max_length=25)),
                ('Telefone', models.PositiveIntegerField(blank=True, null=True)),
                ('Celular', models.PositiveIntegerField(blank=True, null=True)),
                ('CEP', models.PositiveIntegerField(blank=True, null=True)),
                ('Tentativas', models.PositiveIntegerField(default=0)),
                ('IdEstado', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.State')),
                ('IdPai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DataRegistro', models.DateTimeField(null=True)),
                ('IdCao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.Dog')),
                ('IdInteressado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdProtetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='IdTamanho',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.Size'),
        ),
    ]
