# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoteNaoCompreSITE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='DataRegistro',
            field=models.DateTimeField(null=True),
        ),
    ]
