# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdoteNaoCompreSITE', '0002_dog_dataregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Info', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='IdRaca',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AdoteNaoCompreSITE.Breed'),
        ),
    ]
