# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AdoteNaoCompreSITE', '0005_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='Peso',
            field=models.FloatField(null=True),
        ),
    ]
